license = "${mod_license}"
issueTrackerURL = "https://github.com/LopyMine/${mod_id}"
modLoader="javafml"
loaderVersion="[1,)"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
side="BOTH"
displayURL = "https://modrinth.com/mod/${mod_id}"
logoFile = "icon/icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "mossylib"
type = "required"
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "inventory_particles"
type = "required"
versionRange = "[1.3.2,)"
ordering = "NONE"
side = "BOTH"